name: econenv
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - tensorflow=2.14.0
  - cudatoolkit=11.8 
  - pytorch::pytorch=2.1.0
  - pytorch::torchvision
  - pytorch::torchaudio
  - nvidia::cuda-nvcc
  - pip
  - pip:
      - qkeras==0.9.0
      - keras==2.14.0
      - pyparsing==3.2.0 # below are added manually
      - matplotlib==3.9.4
      - mplhep==0.3.55
      - imblearn
      - fsspec_xrootd==0.4.0
      - coffea==0.7.20
      - setuptools==65.5.0
